### PR TITLE
Migrate to Swift 3 + Add step by step set up guide

### PR DESCRIPTION
**Pull request by haxpor**
Migrated to Swift 3, and Added step by step setup guide (both in terms of code, and dashboard on developer account).

Notable notes are as follows
* Particular code (commented in pushed code-based) as noted in README.md file still cannot be found a good migrating code for Swift 3. But this code doesn't effect the application's functionality as tested on iOS 10.2.
* Avoid using CocoaPod beta version as you will probably find error when `pod install`. Stick with release version.
* `Podfile.lock` is now included in the index. This will make sure the right working version of dependencies will be fetched.
* Tested building on both Xcode 8.2, and Xcode beta 8.2 on iOS 10.2 device.
* Tested connection with server both in Singapore and Hongkong. It works great!
* As tested, the connection to shadowsocks is always on even you turn off display for long time, or even turn off WiFi/Cellular data, then turn back on again. It will be instant connected.

### CODE REVIEW

**Comment by jwenlee** [comment]
cool

**Comment by jiangyancong** [comment]
good job.

**Comment by huayu0723** [comment]
Nice job. Save me lots of time!

**Comment by icodesign** [comment]
Awesome. Thank you!

**Pull request merged**
